server:
  port: 9090
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/task/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
logging:
  level:
    org.springframework.cloud.gateway: DEBUG

